swagger: "2.0"
info:
  description: "Draft for MaaS (Matomat as a Service)"
  version: "0.0.1"
  title: "MaaS"
host: "maas.k4cg.org"
basePath: "/v0"
tags:
- name: "users"
  description: "User management related operations"
- name: "drinks"
  description: "Drink related operations"
- name: "credits"
  description: "Credits related operations"
schemes:
- "https"
paths:
  /drinks:
    get:
      tags:
      - "drinks"
      summary: "List all available drinks"
      description: ""
      operationId: "getDrinkList"
      produces:
      - "application/json"
      responses:
        200:
          description: List of drink objects
          schema:
            type: array
            items:
              $ref: "#/definitions/Drink"
        403:
          description: "Not allowed"
        404:
          description: "No drinks available"
  /drinks/{drinkid}:
    get:
      tags:
      - "drinks"
      summary: "Get a certain drink"
      description: ""
      operationId: "getDrink"
      produces:
      - "application/json"
      parameters:
      - name: "drinkid"
        in: "path"
        description: "The ID of the drink that needs to be fetched."
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Drink"
        403:
          description: "Not allowed"
        404:
          description: "Unknown drink"
  /drinks/{drinkid}/consume:
    get:
      tags:
      - "drinks"
      summary: "Consumes a drink"
      description: "Consumes a drink and subtracts the cost of the drink from the credit of the user. If not enough credit exists the operation will be rejected"
      operationId: "consumeDrink"
      produces:
      - "application/json"
      parameters:
      - name: "drinkid"
        in: "path"
        description: "The ID of the drink that should be consumed."
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
        403:
          description: "Not allowed"
        404:
          description: "Unknown drink"  
        412:
          description: "Not enough credits to consume drink"
  /users:
    get:
      tags:
      - "users"
      summary: "List all users"
      description: ""
      operationId: "getUserList"
      produces:
      - "application/json"
      responses:
        200:
          description: List of user objects
          schema:
            type: array
            items:
              $ref: "#/definitions/User"
        403:
          description: "Not allowed"
        404:
          description: "No drinks available"
    post:
      tags:
      - "users"
      summary: "Add a new user"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "User creation succeeded"
        403:
          description: "Not allowed"
        405:
          description: "Invalid input"
  /users/{userid}:
    get:
      tags:
      - "users"
      summary: "Get user by user ID"
      description: ""
      operationId: "getUserByID"
      produces:
      - "application/json"
      parameters:
      - name: "userid"
        in: "path"
        description: "The user ID that needs to be fetched."
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        400:
          description: "Invalid username supplied"
        403:
          description: "Not allowed"
        404:
          description: "User not found"
    put:
      tags:
      - "users"
      summary: "Update user"
      description: "This can only be done by the logged in user."
      operationId: "updateUser"
      produces:
      - "application/json"
      parameters:
      - name: "userid"
        in: "path"
        description: "The ID of the user that needs to be updated"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Updated user object"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        400:
          description: "Invalid user ID supplied"
        403:
          description: "Not allowed"
        404:
          description: "User not found"
    delete:
      tags:
      - "users"
      summary: "Delete user"
      description: "This can only be done by the logged in user or an admin."
      operationId: "deleteUser"
      produces:
      - "application/json"
      parameters:
      - name: "userid"
        in: "path"
        description: "The ID of the user to be deleted"
        required: true
        type: "string"
      responses:
        400:
          description: "Invalid user ID supplied"
        403:
          description: "Not allowed"
        404:
          description: "User not found"
  /users/{userid}/login:
    get:
      tags:
      - "users"
      summary: "Logs user into the Matomat service."
      description: "Logs user into the Matomat service. TODO add credentials transfer definition (headers?)"
      operationId: "loginUser"
      produces:
      - "application/json"
      parameters:
      - name: "userid"
        in: "path"
        description: "The ID of the user that should be logged in"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid username/password supplied"
  /users/{userid}/logout:
    get:
      tags:
      - "users"
      summary: "Logs out current logged in user session"
      description: ""
      operationId: "logoutUser"
      produces:
      - "application/json"
      parameters:
      - name: "userid"
        in: "path"
        description: "The ID of the user that should be logged out"
        required: true
        type: "string"
      responses:
        default:
          description: "successful operation"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      username:
        type: "string"
      password:
        type: "string"
      credits:
        type: "number"
        format: "float"
  Drink:
    description: "Represenation of a drink, containing its name and cost (in credits)."
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      name:
        type: "string"
      cost:
        type: "number"
        format: "float"