swagger: "2.0"
info:
  description: "Draft for MaaS (Matomat as a Service)"
  version: "0.0.1"
  title: "MaaS"
host: "maas.k4cg.org"
basePath: "/v0"
tags:
- name: "users"
  description: "User management related operations"
- name: "drinks"
  description: "Drink related operations"
schemes:
- "https"
paths:
  /drinks:
    get:
      tags:
      - "drinks"
      summary: "List all available drinks"
      description: ""
      operationId: "getDrinkList"
      produces:
      - "application/json"
      responses:
        200:
          description: List of drink objects
          schema:
            type: array
            items:
              $ref: "#/definitions/Drink"
        403:
          description: "Not allowed"
        404:
          description: "No drinks available"
  /drinks/stats:
    get:
      tags:
      - "drinks"
      summary: "Get consumption stats of all drinks"
      description: "Get the matomat stats for all drinks."
      operationId: "getTotalDrinkStats"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation TODO define response"
        403:
          description: "Not allowed"
        404:
          description: "Drink not found"
  /drinks/{drinkid}:
    get:
      tags:
      - "drinks"
      summary: "Get a certain drink"
      description: ""
      operationId: "getDrink"
      produces:
      - "application/json"
      parameters:
      - name: "drinkid"
        in: "path"
        description: "The ID of the drink that needs to be fetched."
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Drink"
        403:
          description: "Not allowed"
        404:
          description: "Unknown drink"
  /drinks/{drinkid}/consume:
    get:
      tags:
      - "drinks"
      summary: "Consumes a drink"
      description: "Consumes a drink and subtracts the cost of the drink from the credit of the user. If not enough credit exists the operation will be rejected"
      operationId: "consumeDrink"
      produces:
      - "application/json"
      parameters:
      - name: "drinkid"
        in: "path"
        description: "The ID of the drink that should be consumed."
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
        403:
          description: "Not allowed"
        404:
          description: "Unknown drink"  
        412:
          description: "Not enough credits to consume drink"
  /drinks/{drinkid}/stats:
    get:
      tags:
      - "drinks"
      summary: "Get consumption stats"
      description: "Get the matomat stats for a certain drink."
      operationId: "getDrinkStats"
      produces:
      - "application/json"
      parameters:
      - name: "drinkid"
        in: "path"
        description: "The ID of the drink for which to fetch the stats."
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation TODO define response"
        403:
          description: "Not allowed"
        404:
          description: "Drink not found"
  /users:
    get:
      tags:
      - "users"
      summary: "List all users"
      description: ""
      operationId: "getUserList"
      produces:
      - "application/json"
      responses:
        200:
          description: List of user objects
          schema:
            type: array
            items:
              $ref: "#/definitions/User"
        403:
          description: "Not allowed"
        404:
          description: "No drinks available"
    post:
      tags:
      - "users"
      summary: "Add a new user"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "User creation succeeded"
        403:
          description: "Not allowed"
        405:
          description: "Invalid input"
  /users/{userid}:
    get:
      tags:
      - "users"
      summary: "Get user by user ID"
      description: ""
      operationId: "getUserByID"
      produces:
      - "application/json"
      parameters:
      - name: "userid"
        in: "path"
        description: "The user ID that needs to be fetched."
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        400:
          description: "Invalid username supplied"
        403:
          description: "Not allowed"
        404:
          description: "User not found"
    put:
      tags:
      - "users"
      summary: "Update user"
      description: "This can only be done by the logged in user."
      operationId: "updateUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "userid"
        in: "path"
        description: "The ID of the user that needs to be updated"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Updated user object"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        400:
          description: "Invalid user ID supplied"
        403:
          description: "Not allowed"
        404:
          description: "User not found"
    delete:
      tags:
      - "users"
      summary: "Delete user"
      description: "This can only be done by the logged in user or an admin."
      operationId: "deleteUser"
      produces:
      - "application/json"
      parameters:
      - name: "userid"
        in: "path"
        description: "The ID of the user to be deleted"
        required: true
        type: "string"
      responses:
        400:
          description: "Invalid user ID supplied"
        403:
          description: "Not allowed"
        404:
          description: "User not found"
  /users/{userid}/password:
    put:
      tags:
      - "users"
      summary: "Set password for user ID"
      description: "Set password for user ID. This can only be done by the logged in user for the user itself OR by the admin for an arbitrary user."
      operationId: "setPassword"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "userid"
        in: "path"
        description: "The ID of the user do which the password should be changed."
        required: true
        type: "string"
      - name: "password"
        in: "body"
        description: "The new password"
        required: true
        type: "string"
      responses:
        400:
          description: "Invalid user ID supplied"
        403:
          description: "Not allowed"
        404:
          description: "User not found"
  /users/{userid}/login:
    get:
      tags:
      - "users"
      summary: "Logs user into the Matomat service."
      description: "Logs user into the Matomat service. TODO add credentials transfer definition (headers?)"
      operationId: "loginUser"
      produces:
      - "application/json"
      parameters:
      - name: "userid"
        in: "path"
        description: "The ID of the user that should be logged in"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid username/password supplied"
  /users/{userid}/logout:
    get:
      tags:
      - "users"
      summary: "Logs out current logged in user session"
      description: ""
      operationId: "logoutUser"
      produces:
      - "application/json"
      parameters:
      - name: "userid"
        in: "path"
        description: "The ID of the user that should be logged out"
        required: true
        type: "string"
      responses:
        default:
          description: "successful operation"
  /users/{userid}/credits/transfer:
    put:
      tags:
      - "users"
      summary: "Transfer credits."
      description: "Transfers credits from logged in user to given user."
      operationId: "transferCredits"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "userid"
        in: "path"
        description: "The ID of the user to transfer credits to."
        required: true
        type: "integer"
        format: "int32"
      - name: "credits"
        in: "body"
        description: "Amount of credits to transfer"
        required: true
        type: "number"
        format: "float"
      responses:
        400:
          description: "Invalid user ID supplied"
        403:
          description: "Not allowed"
        404:
          description: "User not found"
  /users/{userid}/stats:
    get:
      tags:
      - "users"
      summary: "Get matomat stats for user"
      description: "Get the matomat stats for user. A user can only request the stats for herself."
      operationId: "getUserStats"
      produces:
      - "application/json"
      parameters:
      - name: "userid"
        in: "path"
        description: "The ID of the user for which to fetch the stats."
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation TODO define response"
        403:
          description: "Not allowed"
        404:
          description: "User not found"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      username:
        type: "string"
      credits:
        type: "number"
        format: "float"
  Drink:
    description: "Represenation of a drink, containing its name and cost (in credits)."
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      name:
        type: "string"
      cost:
        type: "number"
        format: "float"